name = "paddlepal"
main = "src/index.ts"
compatibility_date = "2026-02-17"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "paddlepal-db"
database_id = "7c3145ac-c540-4492-8b2e-766c5805a44a"
